// Copyright (c) 2026 tabnas, MIT License

package bnf

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The shared fixtures under rs/tests/oracle/ hold the canonical compiler's
// own refusals, generated by rs/tests/oracle/generate.cjs and graded byte
// for byte by the Rust port; this grades the Go port against them.
func TestOracleRefusalsMatchTypeScript(t *testing.T) {
	dir := filepath.Join("..", "rs", "tests", "oracle")
	files, err := filepath.Glob(filepath.Join(dir, "ir-*.json"))
	if err != nil || len(files) == 0 {
		t.Fatalf("no oracle fixtures under %s: %v", dir, err)
	}
	refusals := 0
	for _, file := range files {
		raw, err := os.ReadFile(file)
		if err != nil {
			t.Fatal(err)
		}
		var fx struct {
			Name      string          `json:"name"`
			IR        json.RawMessage `json:"ir"`
			Opts      ConvertOptions  `json:"opts"`
			PureError *string         `json:"pureError"`
		}
		if err := json.Unmarshal(raw, &fx); err != nil {
			t.Fatalf("%s: %v", file, err)
		}
		if fx.PureError == nil {
			continue
		}
		refusals++
		var ir map[string]any
		if err := json.Unmarshal(fx.IR, &ir); err != nil {
			t.Fatalf("%s: %v", fx.Name, err)
		}
		opts := fx.Opts
		opts.Builtins = true
		_, err = EmitGrammarSpec(oracleGrammar(t, ir), &opts)
		if err == nil || err.Error() != *fx.PureError {
			t.Errorf("%s:\n got  %v\n want %s", fx.Name, err, *fx.PureError)
		}
	}
	if refusals == 0 {
		t.Fatal("no oracle fixture records a refusal")
	}
}

// oracleGrammar reads a fixture's IR, the JSON of the canonical compiler's
// Grammar (a repetition's `max: Infinity` written as null).
func oracleGrammar(t *testing.T, ir map[string]any) *Grammar {
	t.Helper()
	str := func(m map[string]any, k string) string { s, _ := m[k].(string); return s }
	span := func(v any) *SrcSpan {
		m, ok := v.(map[string]any)
		if !ok {
			return nil
		}
		n := func(k string) int { f, _ := m[k].(float64); return int(f) }
		return &SrcSpan{S: n("s"), E: n("e"), R: n("r"), C: n("c")}
	}
	var elem func(v any) *Element
	seqs := func(v any) []Sequence {
		var out []Sequence
		for _, alt := range v.([]any) {
			seq := Sequence{}
			for _, e := range alt.([]any) {
				seq = append(seq, elem(e))
			}
			out = append(out, seq)
		}
		return out
	}
	known := func(m map[string]any, keys string) {
		for k := range m {
			if !strings.Contains(" "+keys+" ", " "+k+" ") {
				t.Fatalf("an oracle IR field %q, which this reader does not know", k)
			}
		}
	}
	elem = func(v any) *Element {
		m := v.(map[string]any)
		known(m, "kind sp literal caseSensitive tokenName text pattern flags name inner min max alts")
		el := &Element{Kind: ElemKind(str(m, "kind")), Sp: span(m["sp"]),
			Literal: str(m, "literal"), TokenName: str(m, "tokenName"), Text: str(m, "text"),
			Pattern: str(m, "pattern"), Flags: str(m, "flags"), Name: str(m, "name")}
		if cs, ok := m["caseSensitive"].(bool); ok {
			el.CaseSensitive, el.HasCaseSens = cs, true
		}
		switch el.Kind {
		case KindTerm, KindRef, KindToken, KindProse, KindRegex:
		case KindOpt, KindStar, KindPlus, KindRep:
			el.Inner = elem(m["inner"])
			if el.Kind == KindRep {
				minF, _ := m["min"].(float64)
				el.Min, el.Max = int(minF), MaxInfinity
				if maxF, ok := m["max"].(float64); ok {
					el.Max = int(maxF)
				}
			}
		case KindGroup:
			el.Alts = seqs(m["alts"])
		default:
			t.Fatalf("an oracle IR element of kind %q, which this reader does not know", el.Kind)
		}
		return el
	}
	g := &Grammar{}
	for _, p := range ir["productions"].([]any) {
		m := p.(map[string]any)
		known(m, "name alts sp nodeKind origin value")
		prod := &Production{Name: str(m, "name"), Alts: seqs(m["alts"]), Sp: span(m["sp"]),
			NodeKind: str(m, "nodeKind"), Origin: str(m, "origin")}
		if va, ok := m["value"].(map[string]any); ok {
			known(va, "kind members")
			prod.Value = &ValueAnnotation{Kind: str(va, "kind")}
			for _, member := range va["members"].([]any) {
				prod.Value.Members = append(prod.Value.Members, member.(string))
			}
		}
		g.Productions = append(g.Productions, prod)
	}
	return g
}
