// Copyright (c) 2026 Richard Rodger and other contributors, MIT License

// The TypeScript compiler is the oracle for this port. Each fixture under
// tests/oracle/ holds an IR exactly as a front-end handed it to the
// canonical `emitGrammarSpec`, the strict-jsonic text TypeScript emitted
// for it (pure-data and recognition shapes), and the TypeScript engine's
// verdict on a few sources. The port must reproduce the text byte for
// byte and the engine verdicts value for value.
//
// The fixtures are generated by a TypeScript harness (see rs/AGENTS.md);
// the grammars are the ones ci/rust/notation-corpus.js in the parser
// repository already proves run on the Rust engine when compiled by
// TypeScript. ORACLE_DIR points the same test at another directory of
// fixtures, which is how the wider abnf corpus is graded.

use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;
use tabnas_bnf::{
    emit_grammar_spec, to_jsonic, to_pure_spec, to_recognition_spec, ConvertOptions, Grammar,
    JsonicOptions,
};

fn fixture_dir() -> PathBuf {
    match std::env::var("ORACLE_DIR") {
        Ok(dir) => PathBuf::from(dir),
        Err(_) => Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("oracle"),
    }
}

fn fixtures() -> Vec<(String, Value)> {
    let dir = fixture_dir();
    let mut out: Vec<(String, Value)> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .filter_map(|entry| {
            let path = entry.ok()?.path();
            if path.extension().and_then(|e| e.to_str()) != Some("json") {
                return None;
            }
            let text = fs::read_to_string(&path).expect("fixture is readable");
            let value: Value = serde_json::from_str(&text).expect("fixture is JSON");
            Some((
                path.file_stem().unwrap().to_string_lossy().into_owned(),
                value,
            ))
        })
        .collect();
    out.sort_by(|a, b| a.0.cmp(&b.0));
    assert!(
        !out.is_empty(),
        "no oracle fixtures under {}",
        dir.display()
    );
    out
}

fn options_of(opts: &Value, builtins: bool) -> ConvertOptions {
    let mut o = ConvertOptions::default();
    if let Some(tag) = opts.get("tag").and_then(Value::as_str) {
        o.tag = Some(tag.to_string());
    }
    if let Some(start) = opts.get("start").and_then(Value::as_str) {
        o.start = Some(start.to_string());
    }
    if let Some(m) = opts.get("marks").and_then(Value::as_bool) {
        o.marks = m;
    }
    if let Some(w) = opts.get("wordKeywords").and_then(Value::as_bool) {
        o.word_keywords = w;
    }
    if let Some(p) = opts.get("provenance").and_then(Value::as_bool) {
        o.provenance = p;
    }
    o.builtins = builtins;
    o
}

/// With ORACLE_DUMP set to a directory, every text the port produced is
/// written there as `<fixture>.<shape>.json`, so a difference can be
/// diffed in full rather than read off the first differing line.
fn dump(name: &str, shape: &str, text: &str) {
    if let Ok(dir) = std::env::var("ORACLE_DUMP") {
        let _ = fs::create_dir_all(&dir);
        let _ = fs::write(Path::new(&dir).join(format!("{name}.{shape}.json")), text);
    }
}

fn first_difference(a: &str, b: &str) -> String {
    let (la, lb): (Vec<&str>, Vec<&str>) = (a.lines().collect(), b.lines().collect());
    for (i, (x, y)) in la.iter().zip(lb.iter()).enumerate() {
        if x != y {
            let lo = i.saturating_sub(3);
            let ctx: Vec<String> = (lo..i).map(|k| format!("      {}", la[k])).collect();
            return format!(
                "line {}:\n{}\n  got:  {}\n  want: {}",
                i + 1,
                ctx.join("\n"),
                x,
                y
            );
        }
    }
    format!("lengths differ: got {} lines, want {}", la.len(), lb.len())
}

/// A fixture whose `pureError` is set records an IR the TypeScript
/// compiler REFUSED, and the message it refused it with. The refusal is
/// as much of the contract as the emitted text: a front-end shows it to
/// the author of the grammar.
fn refusal_of(fx: &Value) -> Option<&str> {
    fx["pureError"].as_str()
}

#[test]
fn emits_the_same_pure_data_spec_as_typescript() {
    let mut failures = Vec::new();
    let mut checked = 0;
    for (name, fx) in fixtures() {
        let grammar: Grammar = serde_json::from_value(fx["ir"].clone())
            .unwrap_or_else(|e| panic!("{name}: IR does not deserialize: {e}"));
        let opts = options_of(&fx["opts"], true);
        if let Some(want_err) = refusal_of(&fx) {
            checked += 1;
            match emit_grammar_spec(&grammar, &opts) {
                Ok(_) => failures.push(format!(
                    "{name}: TypeScript refused the IR ({want_err}) but the port emitted a spec"
                )),
                Err(e) if e.message != want_err => failures.push(format!(
                    "{name}: refusal message differs:\n  got:  {}\n  want: {want_err}",
                    e.message
                )),
                Err(_) => {}
            }
            continue;
        }
        let want = fx["pure"].as_str().expect("pure text");
        match emit_grammar_spec(&grammar, &opts) {
            Err(e) => failures.push(format!("{name}: emit failed: {e}")),
            Ok(spec) => match to_pure_spec(&spec) {
                Err(e) => failures.push(format!("{name}: to_pure_spec failed: {e}")),
                Ok(pure) => {
                    let got = to_jsonic(
                        &pure,
                        JsonicOptions {
                            strict: true,
                            indent: None,
                        },
                    );
                    checked += 1;
                    dump(&name, "pure", &got);
                    if got != want {
                        failures.push(format!(
                            "{name}: pure spec differs at {}",
                            first_difference(&got, want)
                        ));
                    }
                }
            },
        }
    }
    assert!(checked > 0);
    assert!(failures.is_empty(), "{}", failures.join("\n\n"));
}

#[test]
fn emits_the_same_recognition_spec_as_typescript() {
    let mut failures = Vec::new();
    for (name, fx) in fixtures() {
        // A refused IR has no recognition text; the pure test grades the
        // refusal message.
        if refusal_of(&fx).is_some() {
            continue;
        }
        let grammar: Grammar = serde_json::from_value(fx["ir"].clone()).expect("IR");
        let opts = options_of(&fx["opts"], false);
        let spec = match emit_grammar_spec(&grammar, &opts) {
            Ok(spec) => spec,
            Err(e) => {
                failures.push(format!("{name}: emit failed: {e}"));
                continue;
            }
        };
        match (
            to_recognition_spec(&spec),
            fx["recognition"].as_str(),
            fx["recognitionError"].as_str(),
        ) {
            (Ok(rec), Some(want), _) => {
                let got = to_jsonic(
                    &rec,
                    JsonicOptions {
                        strict: true,
                        indent: None,
                    },
                );
                dump(&name, "recognition", &got);
                if got != want {
                    failures.push(format!(
                        "{name}: recognition spec differs at {}",
                        first_difference(&got, want)
                    ));
                }
            }
            (Err(e), _, Some(want_err)) => {
                if e.message != want_err {
                    failures.push(format!(
                        "{name}: recognition error differs:\n  got:  {}\n  want: {}",
                        e.message, want_err
                    ));
                }
            }
            (Ok(_), None, Some(want_err)) => {
                failures.push(format!(
                    "{name}: TypeScript refused recognition ({want_err}) but the port produced one"
                ));
            }
            (Err(e), Some(_), _) => {
                failures.push(format!("{name}: to_recognition_spec failed: {e}"))
            }
            (_, None, None) => failures.push(format!("{name}: fixture has no recognition text")),
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n\n"));
}

/// Cases where the TypeScript ENGINE builds a different value from the
/// same serialized grammar than the Rust engine does. These are engine
/// divergences, not compiler ones: the fixture's own TypeScript-emitted
/// spec, run on the Rust engine, gives exactly what this port's spec
/// gives. Each entry names a fixture and a source. The register is
/// asserted in both directions: a listed case that starts agreeing fails
/// as stale, an unlisted case that starts differing fails as a
/// regression.
///
/// Empty today. `abnf-3` (`R = [ A "@" ] A`, a probe dispatcher) was
/// listed until tabnas/parser#206 (commit a801621) kept the parent's
/// child link on the rule it pushed, as TypeScript and Go do: the Rust
/// engine now returns the same `{ rule: "R", src: "", kids: [] }` the
/// TypeScript engine does, where it used to return the full tree.
const ENGINE_VALUE_DIVERGENCES: &[(&str, &str)] = &[];

/// Cases the TypeScript ENGINE accepts and this engine rejects, from the
/// same serialized document. Like the value register above these are the
/// parser's, not this compiler's: the text both compilers emit for the
/// fixture is byte identical, so there is nothing here to repair.
///
/// `ir-nullable-suffix` is `A = [ "x" ] A [ "y" ] / "z"`, hidden left
/// recursion whose suffix is nullable, so no suffix debt is owed and the
/// tail loop stays greedy. The TypeScript engine recognises `x* z y*`
/// (and returns `undefined` rather than a node for it); this engine
/// rejects every one of those sources with `unexpected`. Read
/// `DIVERGENCE.md`.
const ENGINE_REJECTS_WHAT_TYPESCRIPT_ACCEPTS: &[(&str, &str)] = &[
    ("ir-nullable-suffix", "z"),
    ("ir-nullable-suffix", "xz"),
    ("ir-nullable-suffix", "xzy"),
    ("ir-nullable-suffix", "zy"),
];

fn install(pure: Value) -> tabnas::Tabnas {
    let engine = tabnas::GrammarSpec::from_value(pure).expect("the engine loads the document");
    let mut parser = tabnas::Tabnas::new();
    parser.grammar(&engine).expect("install");
    parser
}

#[test]
fn the_engine_reaches_the_same_verdicts_as_typescript() {
    let mut failures = Vec::new();
    let mut checked = 0;
    let mut diverged: Vec<(String, String)> = Vec::new();
    let mut rejected: Vec<(String, String)> = Vec::new();
    let mut graded: Vec<String> = Vec::new();
    for (name, fx) in fixtures() {
        let Some(cases) = fx["cases"].as_array() else {
            continue;
        };
        if cases.is_empty() {
            continue;
        }
        graded.push(name.clone());
        let grammar: Grammar = serde_json::from_value(fx["ir"].clone()).expect("IR");
        let spec = emit_grammar_spec(&grammar, &options_of(&fx["opts"], true)).expect("emit");
        let ours = install(to_pure_spec(&spec).expect("pure"));
        // The compiler-parity claim is made on ONE engine: TypeScript's
        // spec and this port's spec, both run here, must agree exactly.
        let theirs = install(serde_json::from_str(fx["pure"].as_str().unwrap()).expect("TS spec"));
        for case in cases {
            let source = case["source"].as_str().unwrap();
            let want_accepted = case["accepted"].as_bool().unwrap();
            checked += 1;
            let got = ours.parse(source);
            let cross = theirs.parse(source);
            match (&got, &cross) {
                (Ok(a), Ok(b)) if a.to_json() == b.to_json() => {}
                (Err(a), Err(b)) if a.code == b.code => {}
                _ => failures.push(format!(
                    "{name}: {source:?}: this port's spec and TypeScript's spec disagree on the Rust engine:\n  ours:   {}\n  theirs: {}",
                    got.as_ref().map(|v| v.to_json().to_string()).unwrap_or_else(|e| e.code.clone()),
                    cross.as_ref().map(|v| v.to_json().to_string()).unwrap_or_else(|e| e.code.clone())
                )),
            }
            match got {
                Ok(value) => {
                    if !want_accepted {
                        failures.push(format!(
                            "{name}: {source:?} accepted, TypeScript rejected with {}",
                            case["code"]
                        ));
                    } else if value.to_json() != case["value"] {
                        diverged.push((name.clone(), source.to_string()));
                    }
                }
                Err(e) => {
                    if want_accepted {
                        if ENGINE_REJECTS_WHAT_TYPESCRIPT_ACCEPTS
                            .iter()
                            .any(|(f, sc)| *f == name && *sc == source)
                        {
                            rejected.push((name.clone(), source.to_string()));
                        } else {
                            failures.push(format!(
                                "{name}: {source:?} rejected with {}, TypeScript accepted",
                                e.code
                            ));
                        }
                    } else if Some(e.code.as_str()) != case["code"].as_str() {
                        failures.push(format!(
                            "{name}: {source:?} code {} differs from TypeScript's {}",
                            e.code, case["code"]
                        ));
                    }
                }
            }
        }
    }
    // The committed set always carries engine cases; an external
    // directory of grammar-only fixtures (ORACLE_DIR) legitimately has
    // none, and its parity claim is the two text tests.
    assert!(
        checked > 0 || std::env::var("ORACLE_DIR").is_ok(),
        "no engine cases were graded"
    );
    // The register, both ways. A registered fixture that was not in this
    // run's directory at all is neither stale nor confirmed.
    for (fixture, source) in ENGINE_VALUE_DIVERGENCES {
        if !graded.iter().any(|g| g == fixture) {
            continue;
        }
        if !diverged.iter().any(|(f, s)| f == fixture && s == source) {
            failures.push(format!(
                "{fixture}: {source:?} is registered as an engine value divergence but now agrees; remove it from ENGINE_VALUE_DIVERGENCES"
            ));
        }
    }
    for (fixture, source) in ENGINE_REJECTS_WHAT_TYPESCRIPT_ACCEPTS {
        if !graded.iter().any(|g| g == fixture) {
            continue;
        }
        if !rejected.iter().any(|(f, s)| f == fixture && s == source) {
            failures.push(format!(
                "{fixture}: {source:?} is registered as rejected here and accepted by the TypeScript engine, but this engine now accepts it; remove it from ENGINE_REJECTS_WHAT_TYPESCRIPT_ACCEPTS"
            ));
        }
    }
    for (fixture, source) in &diverged {
        if !ENGINE_VALUE_DIVERGENCES
            .iter()
            .any(|(f, s)| f == fixture && s == source)
        {
            failures.push(format!(
                "{fixture}: {source:?} value differs from the TypeScript engine's and is not a registered engine divergence"
            ));
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n\n"));
}
